#!/usr/bin/env python

"""
Solves problem 2 of Project Euler

    http://projecteuler.net/index.php?section=problems&id=2

Problem statement:

    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""

import itertools

def fibonacci():
    yield 1
    yield 2
    last_values = (1, 2)
    while True:
        next_value = sum(last_values)
        yield next_value
        last_values = (last_values[1], next_value)

not_exceed = 4000000

print sum(
    term
        for term
        in itertools.takewhile(lambda x: x < not_exceed, fibonacci())
        if term % 2 == 0
    )
